language: python
sudo: true
python:
  - '2.7'
  - '3.4'
  - '3.6'

script:
  # prepare python modules
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls
  # prepare reporter
  - curl -fsSL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  # enable other architectures
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # run the tests with Docker Swarm being active
  - docker swarm init
  # python tests
  - PYTHONPATH=src python -m coverage run --branch --source=src -m unittest discover -s tests -v
  # coverage reports
  - python -m coverage report -m
  - python -m coverage xml
  - |
    if [[ "$(python --version 2>&1)" = *2.7* ]]; then
      coveralls
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    fi

jobs:
  include:
    - stage: deploy
      if: branch = master
      script: >
        ./.travis.docker.build.sh   Dockerfile  latest  worker  &&
        ./.travis.docker.deploy.sh  worker

    - stage: deploy
      if: branch = master
      script: >
        ./.travis.docker.build.sh   Dockerfile.armhf  armhf  worker-armhf  &&
        ./.travis.docker.deploy.sh  armhf  worker-armhf

    - stage: deploy
      if: branch = master
      script: >
        ./.travis.docker.build.sh   Dockerfile.aarch64  aarch64   worker-aarch64  &&
        ./.travis.docker.deploy.sh  aarch64   worker-aarch64
